# Generated by Django 2.1.3 on 2018-12-08 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=30)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='address.Address')),
                ('company_name', models.CharField(max_length=50)),
            ],
        ),
    ]
