# Generated by Django 2.1.3 on 2018-12-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('component', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('meal_type', models.CharField(choices=[('SOUP', 'SOUP'), ('PIZZA', 'PIZZA'), ('FISH', 'FISH'), ('BURGER', 'BURGER'), ('OTHER', 'OTHER')], max_length=8)),
                ('components', models.ManyToManyField(to='component.Component')),
            ],
        ),
    ]
