# Generated by Django 2.1.3 on 2018-12-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='_price',
        ),
        migrations.AddField(
            model_name='meal',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
