# Generated by Django 2.1.4 on 2019-01-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_auto_20190121_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
